package org.rights.locker.Services;

import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.util.Map;
import java.util.Objects;

@Slf4j
@Service
public class PDFBuilderService {

    public byte[] buildMetadataPdf(Map<String, ?> meta) {
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.LETTER);
            doc.addPage(page);

            // Margins & layout
            float margin = 54f; // 0.75"
            float y = page.getMediaBox().getHeight() - margin;

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {

                // Header
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_BOLD, 18);
                cs.newLineAtOffset(margin, y);
                cs.showText("Evidence Metadata Report");
                cs.endText();
                y -= 24;

                // Subtitle
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA, 10);
                cs.newLineAtOffset(margin, y);
                cs.showText("Generated by RightsLocker on " +
                        nv(meta, "generatedAt", Instant.now().toString()));
                cs.endText();
                y -= 18;

                // Section: Identity
                y = section(cs, margin, y, "Identity");
                y = kv(cs, margin, y, "Evidence ID",  nv(meta, "evidenceId", null));
                y = kv(cs, margin, y, "Title",        nv(meta, "title", null));
                y = kv(cs, margin, y, "Description",  nv(meta, "description", null));
                y = kv(cs, margin, y, "Status",       nv(meta, "status", null));
                y = kv(cs, margin, y, "Captured At",  nv(meta, "capturedAt", null));
                y = kv(cs, margin, y, "Ingested At",  nv(meta, "ingestedAt", null));
                y -= 6;

                // Section: Original Asset (critical for authenticity)
                y = section(cs, margin, y, "Original Asset (Authoritative Copy)");
                y = kv(cs, margin, y, "S3 Key",       nv(meta, "originalKey", null));
                y = kv(cs, margin, y, "Size (bytes)", nv(meta, "originalSizeB", null));
                y = kv(cs, margin, y, "Hash Algorithm", nv(meta, "hashAlgorithm", "SHA-256"));
                y = kvMono(cs, margin, y, "SHA-256",  nv(meta, "originalSha256", null));
                y -= 6;

                // Section: Redacted Derivative (if present)
                if (meta.get("redactedKey") != null) {
                    y = section(cs, margin, y, "Redacted Derivative");
                    y = kv(cs, margin, y, "S3 Key",        nv(meta, "redactedKey", null));
                    y = kv(cs, margin, y, "Size (bytes)",  nv(meta, "redactedSizeB", null));
                    y -= 6;
                }

                // Section: Share Context
                y = section(cs, margin, y, "Share Context");
                y = kv(cs, margin, y, "Share Token",        nv(meta, "shareToken", null));
                y = kv(cs, margin, y, "Allow Original",     nv(meta, "shareAllowOriginal", null));
                y = kv(cs, margin, y, "Share Expires At",   nv(meta, "shareExpiresAt", null));
                y -= 6;

                // Section: Verification Guidance
                y = section(cs, margin, y, "Verification Guidance");
                y = paragraph(cs, margin, y,
                        "To verify authenticity, independently compute SHA-256 for the ORIGINAL file and " +
                                "compare it byte-for-byte with the value above. If they match, the file has not been altered " +
                                "since the time it was hashed at ingestion. Keep this report with the evidence package."
                );

                // Footnote
                y -= 8;
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_OBLIQUE, 8);
                cs.newLineAtOffset(margin, Math.max(y, margin));
                cs.showText("© RightsLocker — chain-of-custody & integrity tooling");
                cs.endText();
            }

            try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
                doc.save(bos);
                return bos.toByteArray();
            }
        } catch (Exception e) {
            log.warn("PDF build failed", e);
            return new byte[0];
        }
    }

    private static String nv(Map<String, ?> m, String key, String defVal) {
        Object v = m.get(key);
        return v == null ? defVal : Objects.toString(v);
    }

    private static float section(PDPageContentStream cs, float x, float y, String title) throws Exception {
        y -= 12;
        cs.beginText();
        cs.setFont(PDType1Font.HELVETICA_BOLD, 12);
        cs.newLineAtOffset(x, y);
        cs.showText(title);
        cs.endText();
        return y - 8;
    }

    private static float kv(PDPageContentStream cs, float x, float y, String k, String v) throws Exception {
        if (v == null || v.isBlank()) return y;
        cs.beginText();
        cs.setFont(PDType1Font.HELVETICA, 10);
        cs.newLineAtOffset(x, y);
        cs.showText(k + ": " + v);
        cs.endText();
        return y - 14;
    }

    // monospace line for hashes
    private static float kvMono(PDPageContentStream cs, float x, float y, String k, String v) throws Exception {
        if (v == null || v.isBlank()) return y;
        cs.beginText();
        cs.setFont(PDType1Font.COURIER, 10);
        cs.newLineAtOffset(x, y);
        cs.showText(k + ": " + v);
        cs.endText();
        return y - 14;
    }

    private static float paragraph(PDPageContentStream cs, float x, float y, String text) throws Exception {
        // extremely simple line break
        final int maxChars = 90;
        String[] words = text.split("\\s+");
        StringBuilder line = new StringBuilder();
        cs.setFont(PDType1Font.HELVETICA, 10);
        for (String w : words) {
            if (line.length() + w.length() + 1 > maxChars) {
                cs.beginText(); cs.newLineAtOffset(x, y); cs.showText(line.toString()); cs.endText();
                y -= 14; line.setLength(0);
            }
            if (!line.isEmpty()) line.append(' ');
            line.append(w);
        }
        if (!line.isEmpty()) {
            cs.beginText(); cs.newLineAtOffset(x, y); cs.showText(line.toString()); cs.endText();
            y -= 14;
        }
        return y;
    }
}
