services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=RightsLocker'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
      - 'POSTGRES_USER=${DB_USER}'

    ports:
      - '5432'
