spring.application.name=rightslocker
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.security.user.name=none
spring.security.user.password=none

app.jwtExpirationMs=86400000
logging.level.wgu.edu.BrinaBright.Security=DEBUG

logging.level.org.springframework.security=DEBUG
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never