spring.application.name=rightslocker

spring.datasource.url=jdbc:postgresql://db:5432/rightslocker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.security.user.name=none
spring.security.user.password=none
jwt.secret=${JWT_SECRET}
jwt.access-ttl-seconds=86400000
logging.level.wgu.edu.BrinaBright.Security=DEBUG

logging.level.org.springframework.security=DEBUG

