package org.rights.locker.Enums;

public enum CustodyEventType {
    RECEIVED, HASHED, STORED_ORIGINAL, QUEUED, TRANSCODED, REDACTED, STORED_DERIVATIVE, PDF_GENERATED, DOWNLOADED, SHARED, LEGAL_HOLD_ON, LEGAL_HOLD_OFF, THUMBNAIL_GENERATED, REVOKED }
